CREATE DATABASE testtechniquedb;
CREATE USER ialab WITH ENCRYPTED PASSWORD 'stage2023';
GRANT CONNECT ON DATABASE testTechniqueDB TO ialab;
GRANT USAGE ON SCHEMA public TO ialab;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ialab;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ialab;
