# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TestTechniqueReda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testtechnique.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2bd1c69a565f486ba48c74f055eda8ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d0e86c6b761427bba82d1a29fdbb260 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testtechnique.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bd1c69a565f486ba48c74f055eda8ee }}/testtechniquestage2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TestTechniqueReda'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_866fbed61ad74e99846ba845c9d8c11a }}
        images: 'testtechnique.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bd1c69a565f486ba48c74f055eda8ee }}/testtechniquestage2:${{ github.sha }}'